# Generated by Django 4.2.1 on 2023-06-02 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_alter_website_maintenance_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceTaskList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_list_name', models.CharField(default='TASK LIST NAME', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(default='TASK NAME', max_length=200)),
                ('task_list', models.ManyToManyField(to='maintenance.maintenancetasklist')),
            ],
        ),
    ]
