# Generated by Django 4.2.1 on 2023-06-02 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_rename_maintenancetasks_maintenancetask'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceTaskCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_category_name', models.CharField(default='TASK CATEGORY NAME', max_length=200)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
    ]
