# Generated by Django 4.2.1 on 2023-06-02 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_maintenancetaskcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenanceplan',
            options={'verbose_name_plural': 'Maintenance Plans'},
        ),
        migrations.AlterModelOptions(
            name='maintenancetask',
            options={'verbose_name_plural': 'Maintenance Tasks'},
        ),
        migrations.AlterModelOptions(
            name='maintenancetaskcategory',
            options={'verbose_name_plural': 'Maintenance Task Categories'},
        ),
        migrations.AlterModelOptions(
            name='maintenancetasklist',
            options={'verbose_name_plural': 'Maintenance Task Lists'},
        ),
        migrations.AddField(
            model_name='maintenancetask',
            name='task_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maintenance.maintenancetaskcategory'),
        ),
    ]
