# Generated by Django 4.2.1 on 2023-06-02 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0006_alter_maintenanceplan_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceplan',
            name='default_task_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maintenance.maintenancetasklist'),
        ),
    ]
