# Generated by Django 4.2.1 on 2023-06-02 20:38

from django.db import migrations, models
import django.db.models.deletion
import maintenance.models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0007_maintenanceplan_default_task_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenanceplan',
            name='plan_name',
        ),
        migrations.RemoveField(
            model_name='maintenancetask',
            name='task_category',
        ),
        migrations.RemoveField(
            model_name='maintenancetask',
            name='task_list',
        ),
        migrations.RemoveField(
            model_name='maintenancetask',
            name='task_name',
        ),
        migrations.RemoveField(
            model_name='maintenancetaskcategory',
            name='task_category_name',
        ),
        migrations.RemoveField(
            model_name='maintenancetasklist',
            name='task_list_name',
        ),
        migrations.RemoveField(
            model_name='website',
            name='website_name',
        ),
        migrations.RemoveField(
            model_name='website',
            name='website_url',
        ),
        migrations.AddField(
            model_name='maintenanceplan',
            name='name',
            field=models.CharField(default='PLAN NAME', max_length=200),
        ),
        migrations.AddField(
            model_name='maintenancetask',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maintenance.maintenancetaskcategory'),
        ),
        migrations.AddField(
            model_name='maintenancetask',
            name='list',
            field=models.ManyToManyField(to='maintenance.maintenancetasklist'),
        ),
        migrations.AddField(
            model_name='maintenancetask',
            name='name',
            field=models.CharField(default='TASK NAME', max_length=200),
        ),
        migrations.AddField(
            model_name='maintenancetaskcategory',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='maintenancetaskcategory',
            name='name',
            field=models.CharField(default='TASK CATEGORY NAME', max_length=200),
        ),
        migrations.AddField(
            model_name='maintenancetasklist',
            name='name',
            field=models.CharField(default='TASK LIST NAME', max_length=200),
        ),
        migrations.AddField(
            model_name='website',
            name='name',
            field=models.CharField(default='Website Name', max_length=200),
        ),
        migrations.AddField(
            model_name='website',
            name='url',
            field=models.URLField(max_length=500, null=True, validators=[maintenance.models.RequireHttpOrHttpsUrl()]),
        ),
    ]
