# Generated by Django 4.2.1 on 2023-06-02 20:42

from django.db import migrations, models
import maintenance.models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0009_rename_list_maintenancetask_task_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='login_url',
            field=models.URLField(max_length=500, null=True, validators=[maintenance.models.RequireHttpOrHttpsUrl()]),
        ),
    ]
