# Generated by Django 4.2.1 on 2023-06-02 20:43

from django.db import migrations, models
import maintenance.models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0010_website_login_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='login_url',
            field=models.URLField(blank=True, max_length=500, null=True, validators=[maintenance.models.RequireHttpOrHttpsUrl()]),
        ),
    ]
