# Generated by Django 4.2.1 on 2023-06-05 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0012_maintenancegrade_website_maintenance_grade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenancegrade',
            options={'verbose_name_plural': 'Website Maintenance Grades'},
        ),
    ]
