# Generated by Django 4.2.1 on 2023-06-06 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0013_alter_maintenancegrade_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Event Name', max_length=200)),
                ('website', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maintenance.website')),
            ],
            options={
                'verbose_name_plural': 'Website Events',
            },
        ),
    ]
