# Generated by Django 4.2.1 on 2023-06-06 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0014_websiteevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteevent',
            name='event_type',
            field=models.CharField(choices=[('MT', 'Maintenance'), ('UP', 'Update'), ('OT', 'Other')], default='OT', max_length=2),
        ),
    ]
