# Generated by Django 4.2.1 on 2023-06-18 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0015_websiteevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='website',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
