# Generated by Django 4.2.1 on 2023-06-18 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0016_website_description_website_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='websiteevent',
            name='event_type',
        ),
        migrations.AddField(
            model_name='website',
            name='tags',
            field=models.ManyToManyField(to='maintenance.tag'),
        ),
    ]
