# Generated by Django 4.2.1 on 2023-06-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0019_website_maintenance_task_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteevent',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='websiteevent',
            name='worker',
            field=models.CharField(default='Worker Name', max_length=200),
        ),
    ]
