# Generated by Django 4.2.1 on 2023-11-04 07:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0022_alter_websiteevent_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiteevent',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
